<?php
declare(strict_types=1);

$legalPage = [
    'title' => 'Conditions d’utilisation - SmartVision',
    'description' => 'Conditions d’utilisation de SmartVision, lecteur IPTV légal Android TV.',
    'heading' => 'Conditions d’utilisation',
    'intro' => 'Dernière mise à jour : 24 juin 2026. Ces conditions définissent les règles applicables à l’accès et à l’utilisation de SmartVision, application Android TV et service associé.',
    'sections' => [
        ['title' => 'Acceptation', 'paragraphs' => ['En installant, ouvrant, activant ou utilisant SmartVision, l’utilisateur accepte les présentes Conditions d’utilisation. S’il ne les accepte pas, il doit cesser d’utiliser l’application et la supprimer de son appareil.']],
        ['title' => 'Description du service', 'paragraphs' => ['SmartVision est un lecteur IPTV Android TV. Il permet à l’utilisateur d’ajouter ses propres identifiants, liens, playlists, flux, sources ou configurations légalement obtenus auprès de fournisseurs autorisés.', 'SmartVision peut proposer des fonctions de lecture, organisation, catégories, mini lecteur, lecteur plein écran, historique local, favoris, activation de licence, essai gratuit, mode gratuit avec publicité et support technique.']],
        ['title' => 'Ce que SmartVision ne fournit pas', 'items' => ['aucune chaîne de télévision', 'aucun film ou série', 'aucun bouquet TV', 'aucun abonnement IPTV', 'aucune playlist préchargée', 'aucun contenu sportif, cinéma ou premium', 'aucun accès à des contenus piratés ou non autorisés']],
        ['title' => 'Conditions d’accès', 'paragraphs' => ['L’utilisateur doit disposer d’un appareil compatible Android TV, d’une connexion internet stable et de sources de lecture autorisées. Certaines fonctionnalités nécessitent une activation, une licence valide, un essai gratuit actif ou l’acceptation d’un mode gratuit financé par publicité.']],
        ['title' => 'Licence, essai gratuit et mode gratuit avec publicité', 'paragraphs' => ['SmartVision peut proposer une licence payante pour le logiciel, un essai gratuit limité dans le temps, un mode gratuit avec publicité ou des fonctionnalités gratuites de base selon la version distribuée.', 'Sauf mention contraire, une licence SmartVision concerne uniquement le logiciel SmartVision et ne donne droit à aucun contenu audiovisuel.']],
        ['title' => 'Sources et identifiants fournis par l’utilisateur', 'paragraphs' => ['L’utilisateur est seul responsable des sources, identifiants, portails, playlists et flux qu’il ajoute. Il doit s’assurer qu’il dispose des droits et autorisations nécessaires pour accéder aux contenus lus.']],
        ['title' => 'Utilisations interdites', 'items' => ['utiliser SmartVision avec des contenus piratés ou non autorisés', 'contourner des protections, restrictions géographiques ou droits numériques', 'revendre des accès, codes ou contenus sans droits', 'demander au support SmartVision une playlist, un fournisseur pirate ou une méthode d’accès illicite', 'porter atteinte à la sécurité du service ou frauder l’essai gratuit']],
        ['title' => 'Support', 'paragraphs' => ['Le support SmartVision aide sur l’installation, l’activation, la licence et le fonctionnement technique du logiciel. Il ne fournit pas de contenus, de playlists, de fournisseurs IPTV ou d’identifiants tiers.']],
        ['title' => 'Propriété intellectuelle', 'paragraphs' => ['Le site, l’application, les interfaces, logos, textes, bases de données et éléments graphiques de SmartVision sont protégés par les droits de propriété intellectuelle applicables. Toute reproduction, distribution, modification, extraction ou exploitation non autorisée est interdite.', 'Les marques, logos, chaînes, programmes et contenus affichés via les sources de l’utilisateur restent la propriété de leurs titulaires respectifs. Leur affichage technique ne crée aucun partenariat, autorisation ou affiliation avec SmartVision.']],
        ['title' => 'Suspension et résiliation', 'paragraphs' => ['SmartVision peut suspendre ou résilier l’accès à tout ou partie du service en cas de violation des présentes conditions, fraude, abus, tentative de piratage, atteinte à la sécurité, utilisation illicite, défaut de paiement ou demande d’une autorité compétente.']],
        ['title' => 'Limitation de responsabilité', 'paragraphs' => ['SmartVision ne peut pas être tenu responsable des contenus, flux, playlists, fournisseurs tiers, interruptions de réseaux, incompatibilités matérielles, pertes d’accès à des sources tierces ou conséquences d’une utilisation illicite par l’utilisateur.', 'SmartVision ne garantit pas que tous les formats vidéo, codecs, serveurs, playlists ou identifiants tiers fonctionneront sur tous les appareils.']],
        ['title' => 'Droit applicable', 'paragraphs' => ['Les présentes conditions sont soumises au droit français, sous réserve des règles impératives applicables au consommateur. En cas de litige, l’utilisateur est invité à contacter SmartVision à <a class="text-link" href="mailto:contact%40smartvisions.net">contact@smartvisions.net</a> afin de rechercher une solution amiable.', 'Les informations relatives au médiateur de la consommation compétent devront être ajoutées avant publication si elles sont applicables.']],
    ],
];

require dirname(__DIR__) . '/legal_page.php';
